vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        warehouse_images:
            uri_prefix: /uploads/warehouses
            upload_destination: '%kernel.project_dir%/public/uploads/warehouses'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
